# Generated by Django 5.0.7 on 2024-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Legend', 'Legend'), ('Novice', 'Novice'), ('Intermediate', 'Intermediate')], null=True),
        ),
    ]
