# Generated by Django 5.0.7 on 2024-08-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Intermediate', 'Intermediate'), ('Legend', 'Legend'), ('Novice', 'Novice')], null=True),
        ),
    ]
